"""User model updated with payment_token

Revision ID: 33527cf85942
Revises: 8b9fbc73c113
Create Date: 2024-11-19 20:54:49.608087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33527cf85942'
down_revision = '8b9fbc73c113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_token', sa.String(), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.drop_column('razorpay_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('payment_token')

    # ### end Alembic commands ###
