"""Updated Model with payment token field

Revision ID: 941f57bb6815
Revises: 33527cf85942
Create Date: 2024-11-19 20:59:42.336229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941f57bb6815'
down_revision = '33527cf85942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('razorpay_customer_id')

    # ### end Alembic commands ###
