"""deleted some tables and added some fields and methods

Revision ID: c0a091b457b2
Revises: 941f57bb6815
Create Date: 2024-12-01 19:02:35.597932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c0a091b457b2'
down_revision = '941f57bb6815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_exhausted_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_api_restricted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_api_restricted', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.drop_column('credits_exhausted_date')

    op.create_table('payment_methods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(), nullable=False),
    sa.Column('method_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('method_details', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
